#!/usr/bin/env python
import os
import subprocess
import shutil
from os.path import expanduser

def check(j):
    if (j.decode("utf-8").split('.')[-1]) != j.decode("utf-8"):
        return types.get(j.decode("utf-8").split('.')[-1], None)
    else:
        return types[None].get(j.decode("utf-8").split('/')[-1], None)

paths = ["~/dwn",
        "~/msc",
        "~/pix/Unsorted/",
        "~/rom/Unsorted"]

types = {
        "pdf":"~/doc/pdf/",
        "odt":"~/doc/odt/",
        "ods":"~/doc/xls/",
        "xlsx":"~/doc/xls/",
        "png":"~/pix/Unsorted/",
        "gif":"~/pix/gif/",
        "jpg":"~/pix/Unsorted/",
        "jpe":"~/pix/Unsorted/",
        "jpeg":"~/pix/Unsorted/",
        "part":"rm ",
        "4tc":"rm ",
        "xref":"rm ",
        "tmp":"rm ",
        "pyc":"rm ",
        "pyo":"rm ",
        "fls":"rm ",
        "vrb":"rm ",
        "fdb_latexmk":"rm ",
        "bak":"rm ",
        "swp":"rm ",
        "aux":"rm ",
        "log":"rm ",
        "synctex(busy)":"rm ",
        "lof":"rm ",
        "out":"rm ",
        "snm":"rm ",
        "toc":"rm ",
        "bcf":"rm ",
        "xml":"rm ",
        "gz" :"~/doc/arc/",
        "blg":"rm ",
        "bbl":"rm ",
        "zip":"~/doc/arc/",
        "exe":"~/exc/",
        "msi":"~/exc/",
        "jar":"~/exc/",
        "sh" :"~/exc/",
        "apk":"~/pho/apk/",
        "7z" :"~/doc/arc/",
        "iso":"rm ",
        "idx":"rm ",
        "ilg":"rm ",
        "ind":"rm ",
        "txt":"~/doc/man/",
        "html":"~/doc/man/",
        "md" :"~/doc/man/",
        "ms" :"~/doc/src/",
        "tex":"~/doc/src/msc",
        "mu": "~/doc/src/msc",
        "bib":"~/doc/cit/",
        "nes":"~/rom/nes/",
        "smc":"~/rom/snes/",
        "sfc":"~/rom/snes/",
        None: {
            "LICENSE":"~/doc/man",
            "1":"rm ",
            }
        }

for i in paths:
    i = expanduser(i)
    lol = subprocess.check_output(["tree","-N", "-f","-i", i])
    nope = lol.split(b'\n')[1:-3]
    for j in nope:
        #print(j.decode("utf-8"))
        if os.path.isfile(j.decode("utf-8")):
            if not ".git" in j.decode("utf-8"):
                checked = check(j)
                if not checked is None:
                    checked = expanduser(checked)
                    #checked = "~/msc/"
                    if not checked == "rm ":
                      if not j.decode("utf-8") == checked+j.decode("utf-8").split('/')[-1]:
                        print("mkdir -p '{}'".format(checked))
                        subprocess.call("mkdir -p '{}'".format(checked), shell=True)
                        print("mv '{}' '{}'".format(j.decode("utf-8"),checked+j.decode("utf-8").split('/')[-1]))
                        subprocess.call(("mv '{}' '{}'".format(j.decode("utf-8"),checked+j.decode("utf-8").split('/')[-1])), shell=True)
                    else:
                        print(checked+"'"+j.decode("utf-8") +"'")
                        subprocess.call(checked+"'"+j.decode("utf-8") +"'", shell=True)
