#!/usr/bin/env python
import os,sys
import subprocess
import shutil

with open(sys.argv[1]) as fp:
  F = open("/tmp/update.sh","w")   
  F.write("#!/bin/bash\n")
  F.write("pacman -Syyu --noconfirm\n")
  for line in fp:
    print(line)
    if line[0:9] == "[install]":
      F.write("yay -S --noconfirm " + line[9:-1] + '\n')
    if line[0:6] == "[file]":
      F.write("wget -O "+sys.argv[2] + line[6:-1] +" https://raw.githubusercontent.com/bob16795/config/master" + line[6:-1] + "\n")
subprocess.call(['chmod','+x', '/tmp/update.sh'])
F.close()
# subprocess.call(['/tmp/update.sh'])
