#!/bin/bash
declare -i k;
((k==0))
for i in `cat ~/snd/youtube.txt`
do
  
  youtube-dl $i -i --download-archive ~/snd/archive -x --add-metadata -o "~/snd/%(uploader)s/%(album)s/%(title)s.%(ext)s" && sacad_r ~/snd/ 40 cover.jpg &
done
wait
# --audio-format mp3

declare -i k;
((k==0))
for i in `cat ~/vid/youtube.txt`
do
	((k+=1)) && youtube-dl $i --download-archive ~/vid/archive --add-metadata -o ~/Videos/%\(title\)s.%\(ext\)s -f 18 | grep download &
done
# --audio-format mp3
wait

