#!/bin/bash
cd ~/doc/pdf/
rm -r *
cd ~/doc/tmp
echo -E \\section{ELA} > ~/doc/src/ela_master.tex
for i in $(ls ~/doc/src -w 1)
do
  ela=$(echo $i | grep 'ela_*') 
  ela_parsed=$(echo -E \\input{$ela})
  if [ $ela_parsed != "\\input{}" ] 
  then
    if [ $ela_parsed != "\\input{ela_master.tex}" ]
    then
      echo \\subsection{$ela} | sed -s "s/ela_//" | sed -s "s/.tex//g" | sed -s "s/_/ /g"| sed -s  "s/ / /g">> ~/doc/src/ela_master.tex
      echo $ela_parsed >> ~/doc/src/ela_master.tex
      cat ~/doc/src/$ela | sed -s 's/%-// ' > ~/doc/tmp/$ela
      echo compiling $ela
      pdflatex ~/doc/tmp/$ela >> /dev/null
      rm ~/doc/tmp/$ela
    fi
  fi
done
filesort | sh
echo -E \\section{Global} > ~/doc/src/ss_master.tex
for i in $(ls ~/doc/src -w 1)
do
  ss=$(echo $i | grep 'ss_*') 
  ss_parsed=$(echo -E \\input{$ss})
  if [ $ss_parsed != "\\input{}" ] 
  then
    if [ $ss_parsed != "\\input{ss_master.tex}" ]
    then
      echo \\subsection{$ss} | sed -s "s/ss_//" | sed -s "s/.tex//g" | sed -s "s/_/ /g" | sed -s  "s/ / /g" >> ~/doc/src/ss_master.tex
      echo $ss_parsed >> ~/doc/src/ss_master.tex
      cat ~/doc/src/$ss | sed -s 's/%-// ' > ~/doc/tmp/$ss
      echo compiling $ss
      pdflatex ~/doc/tmp/$ss >> /dev/null
      rm ~/doc/tmp/$ss
    fi
  fi
done

echo -E \\phantomsection > ~/doc/src/pdf_master.tex
echo -E \\addcontentsline{toc}{section}{Esseys} >> ~/doc/src/pdf_master.tex
filesort | sh
for i in $(ls ~/doc/src -w 1)
do
  pdf=$(echo $i | grep 'pdf_*') 
  pdf_parsed=$(echo -E \\includepdf[pages=-]{$HOME/doc/pdf/$pdf} | sed -s "s/.tex/.pdf/")
  if [ -z "${pdf}" ]
  then 
    echo lol
  else
    if [ $pdf != "pdf_master.tex" ]
    then
      echo \\phantomsection >> ~/doc/src/pdf_master.tex
      echo \\addcontentsline{toc}{subsection}{$pdf} | sed -s "s/pdf_//" | sed -s "s/.tex//g" | sed -s "s/_/ /g"| sed -s  "s/ / /g">> ~/doc/src/pdf_master.tex
      echo $pdf_parsed >> ~/doc/src/pdf_master.tex
      cat ~/doc/src/$pdf | sed -s 's/%-// ' > ~/doc/tmp/$pdf
      echo compiling $pdf
      pdflatex ~/doc/tmp/$pdf >> /dev/null
      rm ~/doc/tmp/$pdf
    fi
  fi
done
filesort | sh
rm .* >> /dev/null
cd ~/doc/src
echo compiling main
pdflatex main #>> /dev/null
bibtex8 main >> /dev/null
makeindex -q main >> /dev/null
pdflatex main >> /dev/null
pdflatex main >> /dev/null
echo done
filesort | sh
