#!/bin/bash

while true;
do
  MO="MO: $(mondo -c theme)"
  MU="MU: $(mpc current | perl -X -pi -e 's/[^[:ascii:]]//g')"
  VMU=""
  [[ "$(pulsemixer --get-mute)" = "1" ]] && VMU="M"
  VOL="$(pulsemixer --get-volume)"
  VO="VO: ${VOL%% *}$VMU"
  BA="BA: $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "percentage"| sed 's/    percentage:          //')"
  TI="$(date +%H:%M)"
  xsetroot -name "$BA | $VO | $TI "
	sleep .5
done
