#!/bin/bash

while true;
do
  MO=$(mondo -c theme)
  MU=$(mpc current | perl -X -pi -e 's/[^[:ascii:]]//g')
  VO=$(pulsemixer --get-volume)
  BA=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "percentage"| sed 's/    percentage:          //')
  xsetroot -name "MU: $MU | MO: $MO | VO: ${VO%% *} | BA: $BA "
	sleep .5
done
