#!/bin/bash

if [ ! -f ~/scr/updates/2 ]; then
    notify-send "updating"
    for i in {1..2}
    do
      if [ ! -f ~/scr/updates/$i ]; then
       / wget https://raw.githubusercontent.com/bob16795/config/master/scr/updates/$i -O ~/scr/updates/$i
        updateparse ~/scr/updates/$i $HOME
      fi
    done
fi
